version: '3'
services:
  postgres:
    image: 'postgres:9.6-alpine'
    restart: always
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    container_name: postgres-AT
    environment:
      POSTGRES_DB: attendance_tracker_service
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - '5433:5432'
volumes:
  postgres-data: null
